title: "co_mob_diff"
seed: 42
version: "shanghai_lonlat_unet"

trainer:
  accelerator: "gpu"
  devices: [1]
  max_epochs: 200
  val_interval: 40
  ckpt_path: null

dataset:
  name: "shanghai" # beijing, shanghai, etc.
  data_dir: "/path/to/data"
  batch_size:
    train: 1024
    val: 1024
  length:
    train: null
    val: null
  num_workers: 32
  pin_memory: False

model:
  target: "lonlat" # emb, loc, xy, lonlat
  enable_ema: False
  noise_prior: False
  ema_decay: 0.9999
  input_dim: 2
  output_dim: 2 # consistent with input_dim
  resolution: 48
  time_interval: 1800
  weight_decay: 0.03
  lr: 0.0005
  lr_scheduler: "OneCycleLR" # CosineAnnealingLR, OneCycleLR
  T_max: 200
  metrics: ["distance", "radius", "duration", "daily_loc", "cpc", "mape"]
  num_regions: 10906
  noise_sampler:
    hidden_dim: 128
    num_layers: 4
    num_heads: 8
    head_dim: 16
    dropout: 0.1
  diffusion:
    num_steps: 500
    num_sample_steps: 100
    beta_start: 0.0001
    beta_end: 0.05
  unet:
    model_channel: 128
    channel_mult: [1, 2, 2, 2]
    channel_mult_emb: 4
    channels_per_head: 64
    num_blocks: 2
    dropout: 0.1
    guidance_scale: 3
